.github/workflows/publish.yml
Fix typo, missing flag letter P
=> Let github actions build EAP, fix

src/main/java/org/purescript/file/PSFile.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/PSValueDeclaration.kt, src/main/java/org/purescript/psi/ValueReference.kt, src/test/java/org/purescript/LightFindUsageTest.kt, src/test/java/org/purescript/ReferenceTest.kt, src/test/java/org/purescript/features/PSFindUsageProviderTest.kt, src/test/java/org/purescript/psi/PSVarTest.kt
And make the list for choosing which to go to include the parameter list
=> Find all value declarations with same name

src/main/java/org/purescript/file/PSFile.kt, src/main/java/org/purescript/psi/PSImportDeclarationImpl.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/var/ImportedValueReference.kt, src/main/java/org/purescript/psi/var/LocalForeignValueReference.kt, src/main/java/org/purescript/psi/var/LocalValueReference.kt, src/test/java/org/purescript/psi/PSValueDeclarationTest.kt
This might have a slight performance hit, but it will be easier to develop, and fix later.
=> Simplify reference

src/main/java/org/purescript/psi/PSExportedItem.kt, src/main/java/org/purescript/psi/var/ExportedValueReference.kt, src/test/java/org/purescript/psi/var/ExportedValueReferenceTest.kt
https://user-images.githubusercontent.com/5345337/108626329-e51c2f00-744f-11eb-97a1-8fb106ea5a59.mov
=> Exported values – Reference resolution, completion, and find usages

src/main/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspection.kt, src/main/java/org/purescript/parser/PureParsecParser.kt, src/main/java/org/purescript/psi/PSExportedItem.kt, src/main/resources/META-INF/plugin.xml, src/main/resources/inspectionDescriptions/PSUnresolvedReference.html, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt
https://user-images.githubusercontent.com/5345337/108745533-7ddba900-753b-11eb-9f0c-3e6222fbc9e6.mov
=> Add inspection for unresolved exported values

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/psi/PSExportList.kt, src/main/java/org/purescript/psi/PSExportedItem.kt, src/main/java/org/purescript/psi/PSForeignValueDeclaration.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/var/ExportedValueReference.kt, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt, src/test/java/org/purescript/psi/var/ExportedValueReferenceTest.kt
https://user-images.githubusercontent.com/5345337/108889516-c2834500-760c-11eb-8184-32bd81b04182.mov
=> Make exported value reference resolve for foreign import values

src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/import/ImportedValueReference.kt, src/main/java/org/purescript/psi/import/PSImportDeclarationImpl.kt, src/main/java/org/purescript/psi/import/PSImportedItem.kt, src/test/java/org/purescript/psi/PSImportDeclarationImplTest.kt, src/test/java/org/purescript/psi/PSModuleTest.kt, src/test/java/org/purescript/psi/import/ImportedValueReferenceTest.kt
https://user-images.githubusercontent.com/5345337/110171785-84500780-7dfc-11eb-93cf-82fa6f4e279d.mov
=> Support for resolving imported values

src/main/java/org/purescript/ide/folding/PurescriptFoldingBuilder.kt, src/main/java/org/purescript/ide/folding/PurescriptFoldingVisitor.kt, src/main/resources/META-INF/plugin.xml, src/test/java/org/purescript/ide/folding/PurescriptFoldingBuilderTest.kt, test-data/folding/imports_2.purs, test-data/folding/imports_line_breaks.purs, test-data/folding/imports_single.purs
https://user-images.githubusercontent.com/5345337/110237859-9639c380-7f3e-11eb-94e7-31f4f9aa2128.mov
=> Implement code folding for import declarations

src/main/java/org/purescript/ide/folding/PurescriptFoldingBuilder.kt, src/main/java/org/purescript/ide/folding/PurescriptFoldingVisitor.kt, src/main/resources/META-INF/plugin.xml, src/test/java/org/purescript/ide/folding/PurescriptFoldingBuilderTest.kt, test-data/folding/export_list.purs, test-data/folding/imports_2.purs, test-data/folding/imports_line_breaks.purs, test-data/folding/imports_single.purs
**Implement code folding for import declarations** (https://github.com/intellij-purescript/intellij-purescript/pull/137)
https://user-images.githubusercontent.com/5345337/110241863-6b0d9f00-7f53-11eb-98de-ed96bf181bea.mov
=> Implement code folding for export lists (depends on #137)

src/main/java/org/purescript/lexer/LayoutLexer.kt, src/main/java/org/purescript/parser/PSTokens.kt, src/test/java/org/purescript/lexer/LayoutLexerTest.kt
I use https://github.com/natefaubion/purescript-language-cst-parser as a guide
=> Start to work on a layout lexer

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/imports/ImportedDataReference.kt, src/main/java/org/purescript/psi/imports/PSImportDeclarationImpl.kt, src/test/java/org/purescript/accessors.kt, src/test/java/org/purescript/psi/PSModuleTest.kt, src/test/java/org/purescript/psi/imports/ImportedDataReferenceTest.kt
https://user-images.githubusercontent.com/5345337/111066964-140f4900-84c2-11eb-8947-121478a465bf.mov
=> Add import reference for data declarations

src/main/java/org/purescript/ide/folding/PurescriptFoldingVisitor.kt, src/main/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspection.kt, src/main/java/org/purescript/parser/PSParserDefinition.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/PSNewTypeDeclarationImpl.kt, src/main/java/org/purescript/psi/exports/ExportedDataReference.kt, src/main/java/org/purescript/psi/exports/ExportedModuleReference.kt, src/main/java/org/purescript/psi/exports/ExportedValueReference.kt, src/main/java/org/purescript/psi/exports/PSExportList.kt, src/main/java/org/purescript/psi/exports/PSExportedDataMember.kt, src/main/java/org/purescript/psi/exports/PSExportedDataMemberList.kt, src/main/java/org/purescript/psi/exports/PSExportedItem.kt, src/test/java/org/purescript/psi/exports/ExportedDataReferenceTest.kt, src/test/java/org/purescript/psi/exports/ExportedModuleReferenceTest.kt, src/test/java/org/purescript/psi/exports/ExportedValueReferenceTest.kt, src/test/java/org/purescript/psi/exports/PSExportListTest.kt, src/test/java/org/purescript/psi/exports/PSExportedItemTest.kt
https://user-images.githubusercontent.com/5345337/111077149-b3970080-84ef-11eb-87e2-c5ece7e6df97.mov
=> Add support for export references to data and newtype declarations

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/psi/exports/ExportedDataMemberReference.kt, src/main/java/org/purescript/psi/exports/PSExportedDataMember.kt, src/main/java/org/purescript/psi/exports/PSExportedDataMemberList.kt, src/main/java/org/purescript/psi/exports/PSExportedItem.kt, src/test/java/org/purescript/accessors.kt, src/test/java/org/purescript/psi/exports/ExportedDataMemberReferenceTest.kt, src/test/java/org/purescript/psi/exports/PSExportedDataMemberTest.kt
https://user-images.githubusercontent.com/5345337/111194772-d1319c00-85bb-11eb-80d7-dfaaa540f9c1.mov
=> Add reference support for exported data constructors

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/imports/ImportedClassReference.kt, src/main/java/org/purescript/psi/imports/PSImportDeclarationImpl.kt, src/main/java/org/purescript/psi/imports/PSImportedItem.kt, src/test/java/org/purescript/accessors.kt, src/test/java/org/purescript/psi/PSModuleTest.kt, src/test/java/org/purescript/psi/imports/ImportedClassReferenceTest.kt, src/test/java/org/purescript/psi/imports/ImportedDataReferenceTest.kt, src/test/java/org/purescript/psi/imports/ImportedValueReferenceTest.kt, src/test/java/org/purescript/psi/imports/PSImportDeclarationImplTest.kt
https://user-images.githubusercontent.com/5345337/112203524-ec7f5580-8c12-11eb-90aa-bca50fc8bc2b.mov
I also cleaned up some test files, the commit messages should be clear on what is clean up and what is functionality.
=> Implement import references for class declarations

src/main/java/org/purescript/psi/PSPsiElement.kt, src/main/java/org/purescript/psi/classes/ClassConstraintReference.kt, src/main/java/org/purescript/psi/classes/PSClassConstraint.kt, src/main/java/org/purescript/psi/exports/PSExportedItem.kt, src/main/java/org/purescript/psi/var/PSVar.kt, src/test/java/org/purescript/psi/PSPsiElementTest.kt, src/test/java/org/purescript/psi/classes/ClassConstraintReferenceTest.kt
https://user-images.githubusercontent.com/5345337/112366300-efdd1480-8cd8-11eb-9d97-b69723dd6d03.mov
=> Implement references for class constraints

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/file/PSFile.kt, src/main/java/org/purescript/psi/ModuleReference.kt, src/main/java/org/purescript/psi/PSPsiElement.kt, src/main/java/org/purescript/psi/classes/ClassConstraintReference.kt, src/main/java/org/purescript/psi/exports/ExportedDataReference.kt, src/main/java/org/purescript/psi/exports/ExportedModuleReference.kt, src/main/java/org/purescript/psi/exports/ExportedValueReference.kt, src/main/java/org/purescript/psi/exports/PSExportedItem.kt, src/main/java/org/purescript/psi/typeconstructor/TypeConstructorReference.kt, src/main/java/org/purescript/psi/var/ImportedValueReference.kt, src/main/java/org/purescript/psi/var/LocalForeignValueReference.kt, src/main/java/org/purescript/psi/var/LocalValueReference.kt, src/test/java/org/purescript/accessors.kt, src/test/java/org/purescript/psi/ModuleReferenceTest.kt, src/test/java/org/purescript/psi/PSModuleTest.kt, src/test/java/org/purescript/psi/PSValueDeclarationTest.kt, src/test/java/org/purescript/psi/exports/ExportedModuleReferenceTest.kt, src/test/java/org/purescript/psi/exports/ExportedValueReferenceTest.kt, src/test/java/org/purescript/psi/exports/PSExportListTest.kt, src/test/java/org/purescript/psi/exports/PSExportedItemTest.kt, src/test/java/org/purescript/psi/imports/ImportedDataReferenceTest.kt, src/test/java/org/purescript/psi/imports/PSImportDeclarationImplTest.kt, src/test/java/org/purescript/psi/imports/PSImportedClassTest.kt, src/test/java/org/purescript/psi/imports/PSImportedDataTest.kt, src/test/java/org/purescript/psi/imports/PSImportedKindTest.kt, src/test/java/org/purescript/psi/imports/PSImportedOperatorTest.kt, src/test/java/org/purescript/psi/imports/PSImportedTypeTest.kt, src/test/java/org/purescript/psi/imports/PSImportedValeTest.kt, src/test/java/org/purescript/psi/typeconstructor/TypeConstructorReferenceTest.kt
https://user-images.githubusercontent.com/5345337/112808707-92025100-9079-11eb-8d31-130a65434e11.mov
=> Implement navigation between type synonyms and type constructors (depends on #171)

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/file/PSFile.kt, src/main/java/org/purescript/psi/ModuleReference.kt, src/main/java/org/purescript/psi/PSPsiElement.kt, src/main/java/org/purescript/psi/classes/ClassConstraintReference.kt, src/main/java/org/purescript/psi/exports/ExportedDataReference.kt, src/main/java/org/purescript/psi/exports/ExportedModuleReference.kt, src/main/java/org/purescript/psi/exports/ExportedValueReference.kt, src/main/java/org/purescript/psi/exports/PSExportedItem.kt, src/main/java/org/purescript/psi/typeconstructor/TypeConstructorReference.kt, src/main/java/org/purescript/psi/var/ImportedValueReference.kt, src/main/java/org/purescript/psi/var/LocalForeignValueReference.kt, src/main/java/org/purescript/psi/var/LocalValueReference.kt, src/test/java/org/purescript/accessors.kt, src/test/java/org/purescript/psi/ModuleReferenceTest.kt, src/test/java/org/purescript/psi/PSModuleTest.kt, src/test/java/org/purescript/psi/PSValueDeclarationTest.kt, src/test/java/org/purescript/psi/exports/ExportedModuleReferenceTest.kt, src/test/java/org/purescript/psi/exports/ExportedValueReferenceTest.kt, src/test/java/org/purescript/psi/exports/PSExportListTest.kt, src/test/java/org/purescript/psi/exports/PSExportedItemTest.kt, src/test/java/org/purescript/psi/imports/ImportedDataReferenceTest.kt, src/test/java/org/purescript/psi/imports/PSImportDeclarationImplTest.kt, src/test/java/org/purescript/psi/imports/PSImportedClassTest.kt, src/test/java/org/purescript/psi/imports/PSImportedDataTest.kt, src/test/java/org/purescript/psi/imports/PSImportedKindTest.kt, src/test/java/org/purescript/psi/imports/PSImportedOperatorTest.kt, src/test/java/org/purescript/psi/imports/PSImportedTypeTest.kt, src/test/java/org/purescript/psi/imports/PSImportedValeTest.kt, src/test/java/org/purescript/psi/typeconstructor/TypeConstructorReferenceTest.kt
https://user-images.githubusercontent.com/5345337/112828214-b5d09180-908f-11eb-9423-0341d07992f8.mov
=> Implement completion for module names in import declarations (depends on #172)

src/main/java/org/purescript/psi/imports/ImportedValueReference.kt, src/test/java/org/purescript/psi/imports/ImportedValueReferenceTest.kt
https://user-images.githubusercontent.com/5345337/112850772-9a26b480-90aa-11eb-8593-2903c8500042.mov
=> Implement navigation between class members and imported values

src/main/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspection.kt, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt
=> Implement inspections for unresolved expression constructor

src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/PSPsiFactory.kt, src/main/java/org/purescript/psi/expression/ExpressionConstructorReference.kt, src/main/java/org/purescript/psi/expression/ImportExpressionConstructorQuickFix.kt, src/test/java/org/purescript/psi/expression/ImportExpressionConstructorQuickFixTest.kt
https://user-images.githubusercontent.com/5345337/113473752-d6bc2c80-946b-11eb-8150-be3bc4bbe6ba.mov
This is a kind of MVP for this functionality, there are still a lot of improvements that can be done.
=> Implement quick fix for importing expression constructors

src/main/java/org/purescript/psi/expression/ExpressionConstructorReference.kt, src/test/java/org/purescript/psi/expression/ExpressionConstructorReferenceTest.kt
https://user-images.githubusercontent.com/5345337/114298044-9f293200-9ab4-11eb-92cd-e768d9314e86.mov
=> Implement navigation between qualified expression constructors ans data/newtype declarations

src/main/java/org/purescript/ide/actions/CreateFileAction.kt, src/test/java/org/purescript/ide/actions/CreateFileActionTest.kt
=> Create valid module names when creating files

build.gradle, src/main/java/org/purescript/file/ExportedValuesIndex.kt, src/main/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspection.kt, src/main/java/org/purescript/psi/var/ImportedValueReference.kt, src/main/resources/META-INF/plugin.xml, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt, src/test/java/org/purescript/psi/expression/ImportQuickFixTest.kt
https://user-images.githubusercontent.com/72190/114414125-d8de6380-9bae-11eb-98c6-0221748fc135.mp4
=> Import values from quick fix

src/main/java/org/purescript/file/ExportedConstructorsIndex.kt, src/main/java/org/purescript/file/ExportedValuesIndex.kt
The file indexes now do not depend on information outside of the files.
This is needed to conform with there API.
But this means that we now have a small regression where we don't list possible imports from files that reexports whole modules-
=> Fix file index

src/main/java/org/purescript/psi/PSLetImpl.kt, src/main/java/org/purescript/psi/expression/ExpressionIdentifierReference.kt, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt
https://user-images.githubusercontent.com/72190/115142538-9a2f2a00-a042-11eb-8fb3-409d5be14b19.mp4
=> Implement reference for let outside of do

src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt
=> Add test that checks that references can be found through reexported

src/main/java/org/purescript/psi/expression/ExpressionIdentifierReference.kt, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt
https://user-images.githubusercontent.com/72190/116280534-120afc00-a789-11eb-8c01-c9e5b027930f.mp4
=> Fix import class members

src/main/java/org/purescript/parser/PureParsecParser.kt
like so
```purescript
module Main (MyData()) where
data MyData = NotExported
```
=> Allow to export data declaration with empty parenthesis

src/main/java/org/purescript/file/ModuleNameIndex.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/PSPsiElement.kt, src/main/java/org/purescript/psi/exports/ExportedOperatorReference.kt, src/main/java/org/purescript/psi/exports/PSExportedItem.kt, src/test/java/org/purescript/features/LightFindUsageTest.kt, src/test/java/org/purescript/features/PSFindUsageProviderParserTest.kt, src/test/java/org/purescript/ide/inspections/PSUnresolvedReferenceInspectionTest.kt
https://user-images.githubusercontent.com/72190/116807264-7e438200-ab32-11eb-8545-642d3ae07a5e.mp4
=> Find usages even of reexported operators

src/main/java/org/purescript/features/PSFindUsageProvider.kt, src/main/java/org/purescript/parser/PSElements.kt, src/main/java/org/purescript/parser/PSParserDefinition.kt, src/main/java/org/purescript/parser/PureParsecParser.kt, src/main/java/org/purescript/psi/PSExternDataDeclarationImpl.kt, src/main/java/org/purescript/psi/PSForeignDataDeclaration.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/imports/PSImportDeclarationImpl.kt, src/main/java/org/purescript/psi/typeconstructor/TypeConstructorReference.kt, src/test/java/org/purescript/accessors.kt, src/test/java/org/purescript/psi/typeconstructor/TypeConstructorReferenceTest.kt, test-data/parser/FunWithFunDeps.txt, test-data/parser/MutRec2.txt, test-data/parser/MutRec3.txt, test-data/parser/PrimedTypeName.txt
https://user-images.githubusercontent.com/5345337/117484474-65d6cb80-af67-11eb-9bf8-998be6e83eb7.mov
=> Implement navigation for foreign data declarations

build.gradle, src/main/java/org/purescript/file/ExportedConstructorsIndex.kt, src/main/java/org/purescript/ide/formatting/ImportMerger.kt, src/main/java/org/purescript/ide/formatting/PurescriptImportOptimizer.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/PSPsiFactory.kt, src/main/java/org/purescript/psi/expression/ConstructorReference.kt, src/main/java/org/purescript/psi/expression/ExpressionIdentifierReference.kt, src/main/java/org/purescript/psi/expression/ImportQuickFix.kt, src/main/java/org/purescript/psi/imports/PSImportDeclarationImpl.kt, src/main/java/org/purescript/psi/imports/PSImportedItem.kt, src/main/java/org/purescript/psi/typeconstructor/TypeConstructorReference.kt, src/main/resources/META-INF/plugin.xml, src/test/java/org/purescript/ide/formatting/ImportMergerTest.kt, src/test/java/org/purescript/ide/formatting/PurescriptImportOptimizerTest.kt, src/test/java/org/purescript/psi/expression/ImportQuickFixTest.kt
https://user-images.githubusercontent.com/5345337/118146686-24369c80-b40f-11eb-8e8d-a89f77862c15.mov
=> Implement optimize imports

src/main/java/org/purescript/PurescriptLiveTemplateContext.kt, src/main/resources/META-INF/plugin.xml, src/main/resources/liveTemplates/Purescript.xml
https://user-images.githubusercontent.com/72190/118166407-bb0e5380-b425-11eb-9363-129ed19392b6.mp4
=> Live templates for instance and case2

src/main/java/org/purescript/ide/formatting/ImportMerger.kt, src/main/java/org/purescript/ide/formatting/PurescriptImportOptimizer.kt, src/main/java/org/purescript/psi/PSModule.kt, src/main/java/org/purescript/psi/PSPsiFactory.kt, src/test/java/org/purescript/ide/formatting/ImportMergerTest.kt, src/test/java/org/purescript/ide/formatting/PurescriptImportOptimizerTest.kt
https://user-images.githubusercontent.com/72190/118401108-a8ce2880-b664-11eb-91d7-1c4fe0c001e4.mp4
=> Sort imports with data members and whitespace formatting

src/main/kotlin/org/purescript/ide/purs/PursIdeQuickFix.kt, src/main/kotlin/org/purescript/ide/purs/PursIdeRebuildExternalAnnotator.kt, src/main/kotlin/org/purescript/ide/purs/PursIdeRebuildInspection.kt, src/main/kotlin/org/purescript/ide/purs/Response.kt, src/main/resources/META-INF/plugin.xml
https://user-images.githubusercontent.com/72190/121815133-26da1b00-cc75-11eb-93a4-64f4d4fa02bb.mp4
=> Purs ide annotation and suggestions

src/main/kotlin/org/purescript/ide/refactoring/PSInline.kt, src/main/kotlin/org/purescript/ide/refactoring/PSInlinePSValueDeclaration.kt, src/main/kotlin/org/purescript/psi/PSPsiFactory.kt, src/main/kotlin/org/purescript/psi/declaration/PSValueDeclaration.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/org/purescript/ide/refactoring/PSInlineTest.kt
https://user-images.githubusercontent.com/72190/131228022-02f87994-34ea-44aa-a31f-b145c2ab5b45.mp4
=> Implement inline for simple value declarations

src/main/kotlin/org/purescript/keyword/KeywordCompletionContributor.kt, src/main/kotlin/org/purescript/keyword/KeywordCompletionProvider.kt, src/main/resources/META-INF/plugin.xml
=> Add keyword autocomplete with do as first example

lexer/src/main/kotlin/org/purescript/PSLanguage.kt
=> 303 support all members of prim

lexer/src/main/kotlin/org/purescript/PSLanguage.kt
Even when they are not imported
=> Allow Prim.* members

src/main/kotlin/org/purescript/file/ExportedFixityIndex.kt, src/main/kotlin/org/purescript/psi/expression/ExpressionSymbolReference.kt, src/main/kotlin/org/purescript/psi/expression/PSExpressionOperator.kt, src/main/kotlin/org/purescript/psi/expression/PSExpressionSymbol.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/org/purescript/accessors.kt, src/test/kotlin/org/purescript/psi/expression/ImportQuickFixTest.kt
=> Add support for importing operators

src/main/kotlin/org/purescript/psi/expression/ConstructorReference.kt, src/main/kotlin/org/purescript/psi/expression/ExpressionIdentifierReference.kt, src/main/kotlin/org/purescript/psi/expression/ExpressionSymbolReference.kt, src/main/kotlin/org/purescript/psi/expression/ImportQuickFix.kt, src/main/kotlin/org/purescript/psi/typeconstructor/TypeConstructorReference.kt, src/test/kotlin/org/purescript/psi/expression/ImportQuickFixTest.kt
=> 333 add import quick fix that are "open" like `import prelude`

src/main/kotlin/org/purescript/psi/PSPsiFactory.kt, src/main/kotlin/org/purescript/psi/PSValue.kt, src/main/kotlin/org/purescript/psi/base/PSPsiElement.kt, src/main/kotlin/org/purescript/psi/base/PSStubbedElement.kt, src/main/kotlin/org/purescript/psi/declaration/MoveValueDeclarationRefactoring.kt, src/main/kotlin/org/purescript/psi/declaration/PSValueDeclaration.kt, src/main/kotlin/org/purescript/psi/declaration/ValueDeclarationMoveHandlerDelegate.kt, src/main/kotlin/org/purescript/psi/expression/PSExpressionWhere.kt, src/main/kotlin/org/purescript/psi/imports/PSImportedItem.kt, src/main/kotlin/org/purescript/psi/module/Module.kt, src/main/kotlin/org/purescript/psi/module/ModuleNameIndex.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/org/purescript/accessors.kt, src/test/kotlin/org/purescript/psi/declaration/PSValueDeclarationTest.kt
https://user-images.githubusercontent.com/72190/211907848-b8d4ccff-d59d-44d3-9714-beb681f44cc2.mp4
https://user-images.githubusercontent.com/72190/212119481-fb0681e0-855f-47b7-abfc-9713e7dc2f17.mp4
=> Add first version of moving value declarations

src/main/kotlin/org/purescript/module/declaration/value/expression/identifier/ImportableCompletionProvider.kt, src/test/kotlin/org/purescript/module/declaration/value/expression/ExpressionIdentifierCompletionContributorTest.kt
=> Autocomplete implicit imports

src/main/kotlin/org/purescript/run/purs/PursIdeRebuildExternalAnnotator.kt
=> Use purs-ide rebuild API without temp files saving FFI files

src/main/kotlin/org/purescript/run/spago/Spago.kt
Added new json serializer that spago outputs, and new library analyze rules.
It is also compatible with legacy version.
Fix #400, Fix #398
=> Add spago@next support
